Movesense integration
cph-cachet/carp_studies_app pull request #234
Opened 2024-03-03 18:55 UTC by bardram

This PR contains all the changes from PR #229 PLUS the following:

* support for the Movesense Device using the new carp_movesense_package 
* showing Movesense HR data in the HR dataviz (in addition to the Polar HR data)
* a test protocol showing how to use the movesense device (in local deployment mode)
* more robust handling if some local resources (like informed consent) isn't available
* better handling of connecting to Bluetooth devices
* fix of #157

2024-03-03 21:05 UTC, bardram commented
You should ignore the GitGuardian Security Checks - the "secrets" are a couple of API Key for the weather and air quality APIs, so not really secrets as such. And - they have been deleted again.

2024-03-12 23:56 UTC, LarsRefsgaard commented
as long as it's not building on ios we can't really accept the pr

2024-04-24 12:09 UTC, SlimShadyIAm requested changes

2024-04-24 12:09 UTC, SlimShadyIAm commented on CHANGELOG.md
> +
we should probably update this more

2024-04-24 12:09 UTC, SlimShadyIAm commented on lib/ui/cards/distance_card.dart
> +          // tooltipBgColor: Colors.grey.withOpacity(0.1),
can this be removed?

2024-04-25 12:05 UTC, SlimShadyIAm approved these changes

2024-04-25 12:52 UTC, merged